INSERT INTO USUARIO_TABLE U (U.ID, U.NOME, U.DOB, U.SEXO, U.EMAIL, U.STATUS, U.LOGIN, U.SENHA) 
VALUES (USUARIO_SEQUENCE.NEXTVAL, 'MARIA GARCIA', '31/12/1935', 'F', 'maria.garcia@gmail.com', 1, 'maria', 'garcia');

INSERT INTO USUARIO_TABLE U (U.ID, U.NOME, U.DOB, U.SEXO, U.EMAIL, U.STATUS, U.LOGIN, U.SENHA)
VALUES (USUARIO_SEQUENCE.NEXTVAL, 'WILLIAN QUEIROZ', '23/3/1973', 'M', 'willian.queiroz@yahoo.com.br', 1, 'willian', 'queiroz');

INSERT INTO USUARIO_TABLE U (U.ID, U.NOME, U.DOB, U.SEXO, U.EMAIL, U.STATUS, U.LOGIN, U.SENHA)
VALUES (USUARIO_SEQUENCE.NEXTVAL, 'ANNA PAULA PADRÃO', '5/5/1985', 'F', 'padrao@gmail.com', 2, 'anna', 'padrao');

INSERT INTO USUARIO_TABLE U (U.ID, U.NOME, U.DOB, U.SEXO, U.EMAIL, U.STATUS, U.LOGIN, U.SENHA)
VALUES (USUARIO_SEQUENCE.NEXTVAL, 'JOÃO ANTÔNIO FERREIRA', '21/1/1991', 'M', 'ferreira16@hotmail.com', 2, 'joao', 'joao');

INSERT INTO USUARIO_TABLE U (U.ID, U.NOME, U.DOB, U.SEXO, U.EMAIL, U.STATUS, U.LOGIN, U.SENHA)
VALUES (USUARIO_SEQUENCE.NEXTVAL, 'JOANNA', NULL, NULL, NULL, NULL, 'joanna', 'joanna');

COMMIT;

SELECT * FROM USUARIO_TABLE;

